# Generated by Django 4.2.14 on 2024-09-25 08:39

from django.db import migrations,models
from django.conf import settings  # If using AUTH_USER_MODEL in migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
        ('admin', '0001_initial'),  # Adjust based on your Django version's admin migrations

    ]

