# Generated by Django 5.0.7 on 2024-07-17 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gensurvapp', '0002_rename_title_todoitem_name_remove_todoitem_completed_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='completed',
            new_name='complete',
        ),
    ]
