# Generated by Django 4.2.14 on 2024-09-25 15:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gensurvapp', '0007_alter_todoitem_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metadata_file', models.FileField(upload_to='uploads/metadata/')),
                ('antibiotics_file', models.FileField(blank=True, null=True, upload_to='uploads/antibiotics/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads/fastq/')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_fastq_files', to='gensurvapp.submission')),
            ],
        ),
        migrations.AddField(
            model_name='submission',
            name='fastq_files',
            field=models.ManyToManyField(blank=True, related_name='submission_fastq_files', to='gensurvapp.uploadedfile'),
        ),
        migrations.AddField(
            model_name='submission',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to=settings.AUTH_USER_MODEL),
        ),
    ]
