# Generated by Django 4.2.14 on 2024-10-20 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gensurvapp', '0008_submission_uploadedfile_submission_fastq_files_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='fastq_files',
        ),
    ]
