# Generated by Django 4.2.14 on 2024-11-24 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gensurvapp', '0014_remove_submission_antibiotics_file_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SampleFile',
        ),
    ]
