# Generated by Django 4.2.14 on 2024-12-09 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gensurvapp', '0017_analysisresult'),
    ]

    operations = [
        migrations.RenameField(
            model_name='analysisresult',
            old_name='summary',
            new_name='error_message',
        ),
        migrations.RemoveField(
            model_name='analysisresult',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='analysisresult',
            name='result_file',
        ),
        migrations.RemoveField(
            model_name='analysisresult',
            name='sample_file',
        ),
        migrations.AddField(
            model_name='analysisresult',
            name='completion_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analysisresult',
            name='result_directory',
            field=models.CharField(default='not_set', max_length=255),
        ),
        migrations.AddField(
            model_name='analysisresult',
            name='sample',
            field=models.OneToOneField(blank=True, limit_choices_to={'file_type': 'fastq'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='analysis_result', to='gensurvapp.samplefile'),
        ),
        migrations.AlterField(
            model_name='analysisresult',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('error', 'Error')], default='pending', max_length=20),
        ),
    ]
