# Generated by Django 4.2.14 on 2024-12-09 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gensurvapp', '0018_rename_summary_analysisresult_error_message_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlasmidIdentResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_id', models.CharField(max_length=100)),
                ('directory_path', models.TextField()),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gensurvapp.submission')),
            ],
        ),
        migrations.CreateModel(
            name='BactopiaResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_id', models.CharField(max_length=100)),
                ('directory_path', models.TextField()),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gensurvapp.submission')),
            ],
        ),
    ]
