# Generated by Django 4.2.14 on 2025-05-14 10:29

from django.db import migrations, models
import gensurvapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('gensurvapp', '0019_plasmididentresult_bactopiaresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='cleaned_file',
            field=models.FileField(blank=True, null=True, upload_to=gensurvapp.models.user_submission_path),
        ),
    ]
