# Generated by Django 4.2.14 on 2025-05-21 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gensurvapp', '0021_alter_samplefile_file_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='resubmission_allowed',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='FileHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_type', models.CharField(max_length=30)),
                ('old_file', models.FileField(upload_to='history/')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gensurvapp.submission')),
            ],
        ),
    ]
