# Generated by Django 4.2.14 on 2025-06-17 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gensurvapp', '0024_alter_filehistory_cleaned_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='warnings',
            field=models.TextField(blank=True, null=True),
        ),
    ]
