# Generated by Django 4.2.14 on 2025-06-18 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gensurvapp', '0025_submission_warnings'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submission',
            old_name='warnings',
            new_name='antibiotics_warnings',
        ),
        migrations.AddField(
            model_name='submission',
            name='fastq_warnings',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='metadata_warnings',
            field=models.TextField(blank=True, null=True),
        ),
    ]
