# Generated by Django 4.2.14 on 2025-06-18 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gensurvapp', '0026_rename_warnings_submission_antibiotics_warnings_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='deletion_requested',
            field=models.BooleanField(default=False),
        ),
    ]
