# Generated by Django 4.2.14 on 2026-03-06 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gensurvapp', '0029_remove_todoitem_user_delete_item_delete_todoitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analysisresult',
            name='sample',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='metadata_file',
        ),
        migrations.AddField(
            model_name='analysisresult',
            name='sample_id',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='submission',
            name='submission_type',
            field=models.CharField(choices=[('bacteria', 'Bacteria'), ('virus', 'Virus')], default='bacteria', max_length=20),
        ),
        migrations.AddField(
            model_name='submission',
            name='submit_to_pipeline',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='analysisresult',
            name='status',
            field=models.CharField(max_length=20),
        ),
        migrations.DeleteModel(
            name='SampleFile',
        ),
    ]
