# Generated by Django 4.2.14 on 2026-02-04 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gensurvapp', '0029_remove_todoitem_user_alter_uploadedfile_submission_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analysisresult',
            name='sample',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='metadata_file',
        ),
        migrations.AddField(
            model_name='analysisresult',
            name='sample_id',
            field=models.CharField(default='unknown', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='submission',
            name='submit_to_pipeline',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='analysisresult',
            name='status',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='submission',
            name='client_total_upload_time',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='network_delay',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='upload_duration',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='uploadedfile',
            name='sample_id',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.DeleteModel(
            name='SampleFile',
        ),
    ]
