# Generated by Django 4.2.14 on 2026-03-09 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gensurvapp', '0030_remove_analysisresult_sample_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedfile',
            name='submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='gensurvapp.submission'),
        ),
    ]
