# Generated by Django 4.2.14 on 2026-02-16 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gensurvapp', '0030_remove_analysisresult_sample_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='submission_type',
            field=models.CharField(choices=[('bacteria', 'Bacteria'), ('virus', 'Virus')], default='bacteria', max_length=20),
        ),
        migrations.AlterField(
            model_name='uploadedfile',
            name='file_type',
            field=models.CharField(choices=[('metadata_raw', 'Metadata Raw'), ('metadata_cleaned', 'Metadata Cleaned'), ('antibiotics_raw', 'Antibiotics Raw'), ('antibiotics_cleaned', 'Antibiotics Cleaned'), ('fastq', 'FASTQ')], max_length=30),
        ),
    ]
