# Generated by Django 4.2.14 on 2026-03-12 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gensurvapp', '0031_alter_uploadedfile_submission'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('singleton_key', models.PositiveSmallIntegerField(default=1, unique=True)),
                ('stats_version', models.PositiveIntegerField(default=1)),
                ('total_submissions', models.PositiveIntegerField(default=0)),
                ('total_metadata_rows', models.PositiveIntegerField(default=0)),
                ('total_fastq_files', models.PositiveIntegerField(default=0)),
                ('total_antibiotics_files', models.PositiveIntegerField(default=0)),
                ('total_unique_sample_identifiers', models.PositiveIntegerField(default=0)),
                ('total_unique_isolate_species', models.PositiveIntegerField(default=0)),
                ('platform_counts', models.JSONField(blank=True, default=dict)),
                ('sir_counts', models.JSONField(blank=True, default=dict)),
                ('mic_numeric_values', models.JSONField(blank=True, default=list)),
                ('map_location_counts', models.JSONField(blank=True, default=list)),
                ('last_recomputed_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='analysisresult',
            name='submission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='analysis_results', to='gensurvapp.submission'),
        ),
        migrations.AddField(
            model_name='submission',
            name='metadata_statistics',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='submission',
            name='client_total_upload_time',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='network_delay',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='upload_duration',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='uploadedfile',
            name='file_type',
            field=models.CharField(choices=[('metadata_raw', 'Metadata Raw'), ('metadata_cleaned', 'Metadata Cleaned'), ('antibiotics_raw', 'Antibiotics Raw'), ('antibiotics_cleaned', 'Antibiotics Cleaned'), ('fastq', 'FASTQ')], max_length=30),
        ),
        migrations.AlterField(
            model_name='uploadedfile',
            name='sample_id',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddIndex(
            model_name='analysisresult',
            index=models.Index(fields=['submission', 'sample_id'], name='gensurvapp__submiss_c904d5_idx'),
        ),
        migrations.AddConstraint(
            model_name='analysisresult',
            constraint=models.UniqueConstraint(condition=models.Q(('submission__isnull', False)), fields=('submission', 'sample_id'), name='uniq_analysisresult_submission_sample'),
        ),
    ]
