# Generated by Django 4.2.14 on 2026-07-22 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gensurvapp', '0032_globalstatistics_analysisresult_submission_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CogdatSampleId',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_id', models.CharField(max_length=100, unique=True)),
                ('imported_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='submission',
            name='submission_type',
            field=models.CharField(choices=[('num-sar_bacteria', 'NUM-SAR/Bacteria'), ('num-sar_virus', 'NUM-SAR/Virus'), ('cogdat', 'COGDAT'), ('gensurv', 'Gensurv')], default='gensurv', max_length=20),
        ),
    ]
