# Generated by Django 4.2.14 on 2026-07-27 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gensurvapp', '0033_cogdatsampleid_alter_submission_submission_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalstatistics',
            name='qc_rank_counts',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
