"""
Django settings for gensurv_project project.

Generated by 'django-admin startproject' using Django 5.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path
import os
#check is neccesary...
from storages.backends.sftpstorage import SFTPStorage
from django.core.files.storage import FileSystemStorage

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-9fmq@_ias7off0o7)1y=sd7@%&*&a9t%^$@y6u#jw2ds*$df&3'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

#ALLOWED_HOSTS = ['gensurv.de', '49.13.219.197']

#ALLOWED_HOSTS = ['*']

ALLOWED_HOSTS = ['gensurv.de', 'static.197.219.13.49.clients.your-server.de','49.13.219.197','localhost']

USE_X_FORWARDED_HOST = True
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    "crispy_forms",
    "crispy_bootstrap4",
    "gensurvapp",
    "register",
    'dbbackup',  # django-dbbackup
    'storages',
    'django.contrib.sites',

    ]
SITE_ID = 1
SITE_URL = 'https://gensurv.de'  # Replace with your actual domain

# Local storage for metadata and antibiotics files
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

DBBACKUP_STORAGE = 'django.core.files.storage.FileSystemStorage'
DBBACKUP_STORAGE_OPTIONS = {'location': '/home/ahcepev1/projects/DBBACKUP_STORAGE'}

DATA_UPLOAD_MAX_MEMORY_SIZE = None#52428800000  # 50GB
DATA_UPLOAD_MAX_NUMBER_FILES = 1000  # Limit to 1000 files per upload
FILE_UPLOAD_MAX_MEMORY_SIZE = 2621440  # 2.5MB threshold before writing to disk

#DEFAULT_FILE_STORAGE = 'storages.backends.sftpstorage.SFTPStorage'
DEFAULT_FILE_STORAGE = 'django.core.files.storage.FileSystemStorage'

SFTP_STORAGE_HOST = 'imgag.de'
SFTP_STORAGE_ROOT = '/home/ahcepev1/fastq_gensurv'
#SFTP_STORAGE_ROOT = '/mnt/storage/ahcepev1/DBBACKUP_STORAGE/data'
SFTP_STORAGE_PARAMS = {
    'username': 'ahcepev1',
    'password': 'Postdoc2023!',
    'port': 22,  # Default SFTP port
}

# Local storage settings for metadata and antibiotics files
LOCAL_STORAGE = FileSystemStorage(location=MEDIA_ROOT)

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
#    'middleware.timing_middleware.UploadTimingMiddleware',  # <- Add this here suggested by the chatgpt to include timing before django uploload recei
]

ROOT_URLCONF = 'gensurv_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
            
        },
    },
]

WSGI_APPLICATION = 'gensurv_project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'gensurv_db',
        'USER': 'gensurv_user',
        'PASSWORD': 'your_password',
        'HOST': 'localhost',
        'PORT': '5432',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')


CRISPY_TEMPLATE_PACK= "bootstrap4"
CRISPY_ALLOWED_TEMPLATE_PACKS = ["bootstrap4"]


# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

#DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
LOGIN_REDIRECT_URL = "/"
LOGOUT_REDIRECT_URL = "/"
LOGIN_URL = '/login/'  # This should be the name of your login page URL

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'file': {
            'level': 'DEBUG',
            'class': 'logging.FileHandler',
            'filename': os.path.join(BASE_DIR, 'django_debug.log'),
            'formatter': 'verbose',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['file'],
            'level': 'DEBUG',
            'propagate': True,
        },
    },
}


# Email settings (using Gmail as an example)
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'vickycees@gmail.com'
EMAIL_HOST_PASSWORD = 'ncas llou pjrh uxsl'

# Default sender email
DEFAULT_FROM_EMAIL = 'vickycees@gmail.com'
# Domain for password reset links
SITE_DOMAIN = 'https://gensurv.de'
#up i have SITE_URL = 'https://gensurv.de'  # Replace with your actual domain

# Optionally add the protocol
PASSWORD_RESET_URL = 'https://gensurv.de'  # Use HTTPS if your site is secure



# Admin email (where registration notifications will be sent)
ADMIN_EMAIL = 'vickycees@gmail.com'

ADMINS = [
    ("Admin", ADMIN_EMAIL),
]

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
]
AUTH_USER_MODEL = 'register.CustomUser'

SESSION_ENGINE = 'django.contrib.sessions.backends.db'  # Or cache, if using cache sessions

DEBUG = True
CRISPY_FAIL_SILENTLY = False
# In settings.py
ENABLE_FTP_UPLOAD = False  # Set to False if you don't want to upload to FTP
