# Generated by Django 5.0.7 on 2024-07-25 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gensurvapp', '0004_todoitem_user'),
        ('gensurvapp', '0005_populate_user_field'),
    ]

    operations = [
    ]
