# Generated by Django 4.2.14 on 2024-11-08 21:32

from django.db import migrations, models
import gensurvapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('gensurvapp', '0010_alter_submission_antibiotics_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='antibiotics_file',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to=gensurvapp.models.user_submission_path),
        ),
        migrations.AlterField(
            model_name='submission',
            name='metadata_file',
            field=models.FileField(max_length=255, upload_to=gensurvapp.models.user_submission_path),
        ),
    ]
