# Generated by Django 4.2.14 on 2024-11-13 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gensurvapp', '0011_alter_submission_antibiotics_file_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='antibiotics_file',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='metadata_file',
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='file_type',
            field=models.CharField(choices=[('metadata', 'Metadata'), ('antibiotics', 'Antibiotics'), ('fastq', 'FASTQ')], default='fastq', max_length=20),
        ),
        migrations.AlterField(
            model_name='uploadedfile',
            name='submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_files', to='gensurvapp.submission'),
        ),
    ]
