# Generated by Django 4.2.14 on 2024-11-24 20:50

from django.db import migrations, models
import django.db.models.deletion
import gensurvapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('gensurvapp', '0015_delete_samplefile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedfile',
            name='file',
            field=models.FileField(upload_to=gensurvapp.models.user_submission_path),
        ),
        migrations.CreateModel(
            name='SampleFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_id', models.CharField(max_length=100)),
                ('file_type', models.CharField(choices=[('metadata', 'Metadata'), ('antibiotics', 'Antibiotics'), ('fastq', 'FASTQ')], max_length=20)),
                ('file', models.FileField(upload_to=gensurvapp.models.user_submission_path)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sample_files', to='gensurvapp.submission')),
            ],
        ),
    ]
