# Generated by Django 4.2.14 on 2024-12-09 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gensurvapp', '0016_alter_uploadedfile_file_samplefile'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('result_file', models.FileField(upload_to='analysis_results/')),
                ('summary', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('sample_file', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_result', to='gensurvapp.samplefile')),
            ],
        ),
    ]
