# Generated by Django 4.2.14 on 2025-05-14 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gensurvapp', '0020_uploadedfile_cleaned_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='samplefile',
            name='file_type',
            field=models.CharField(choices=[('metadata_raw', 'Metadata Raw'), ('metadata_cleaned', 'Metadata Cleaned'), ('antibiotics_raw', 'Antibiotics Raw'), ('antibiotics_cleaned', 'Antibiotics Cleaned'), ('fastq', 'FASTQ')], max_length=30),
        ),
    ]
