# Generated by Django 4.2.14 on 2025-05-21 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gensurvapp', '0022_submission_resubmission_allowed_filehistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='filehistory',
            name='cleaned_file',
            field=models.FileField(blank=True, null=True, upload_to='history/'),
        ),
        migrations.AlterField(
            model_name='filehistory',
            name='file_type',
            field=models.CharField(max_length=50),
        ),
    ]
