# Generated by Django 4.2.14 on 2025-07-04 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gensurvapp', '0027_submission_deletion_requested'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='client_total_upload_time',
            field=models.FloatField(blank=True, help_text='Client-reported total upload time in seconds', null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='network_delay',
            field=models.FloatField(blank=True, help_text='Estimated network + upload delay in seconds', null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='upload_duration',
            field=models.FloatField(blank=True, help_text='Server processing time in seconds', null=True),
        ),
    ]
