# Generated by Django 4.2.14 on 2026-03-06 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gensurvapp', '0028_submission_client_total_upload_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todoitem',
            name='user',
        ),
        migrations.DeleteModel(
            name='Item',
        ),
        migrations.DeleteModel(
            name='TodoItem',
        ),
    ]
